### ISSUE TITLE
Could you plz upload the requirements.txt?

### ISSUE THREAD

**Issue by d0odLe** [ziatdinovmax/MHP_stability#1]
Hi, your team have a great job and congratulations!
But when I want to run your code, I got the problems with the environment.
Could you plz upload the requirements.txt? Thanks. @ziatdinovmax

**Comment by ziatdinovmax** [comment]
You should be able to run them in Google Colab, e.g. https://colab.research.google.com/github/ziatdinovmax/MHP_stability/blob/main/code/%20Time%20Evolution%20Analysis%20of%20Binary%20Systems%20-%20FAPbI3%20and%20CsPbBr3%20(Toluene).ipynb

**Comment by d0odLe** [comment]
Thanks a lot！
